FROM docker.io/rust:1.92-bookworm AS builder
RUN apt-get update && apt-get -y --no-install-recommends install \
    build-essential git clang cmake libclang-dev \
    libsasl2-dev libssl-dev libxxhash-dev zlib1g-dev zlib1g \
    protobuf-compiler

WORKDIR /vector
COPY . .

ARG FEATURES="api,api-client,sources-opentelemetry,sources-kafka,sources-internal_metrics,sinks-kafka,sinks-http,sinks-elasticsearch,transforms-remap,transforms-lua,transforms-log_to_metric,transforms-metric_to_log"

RUN --mount=type=cache,target=/vector/target \
    --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    cargo build --release --bin vector \
    --no-default-features --features "$FEATURES" && \
    cp target/release/vector /vector/vector-bin

FROM docker.io/debian:bookworm-slim
RUN apt-get update && apt-get -y --no-install-recommends install \
    ca-certificates zlib1g libsasl2-2 && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /vector/vector-bin /usr/bin/vector
RUN mkdir -p /var/lib/vector
RUN ["vector", "--version"]
ENTRYPOINT ["/usr/bin/vector"]
